/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Product;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;

/**
 *
 * @author Stefan
 */
public class AdminProductPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductView
     * @param product
     */
    private final Product product;
    public AdminProductPanel(Product product) {
        initComponents();
        this.product = product;
        imageLabel.setIcon(new ImageIcon(product.getImagePath()));
        nameLabel.setText(product.getName());
        brandLabel.setText(product.getBrand());
        priceLabel.setText("$" + String.valueOf(product.getPrice()));
        stockLabel.setText("In stock: " + String.valueOf(product.getStock()));
        if (product.getStock() == 0) {
            stockLabel.setForeground(java.awt.Color.RED);
        } else {
            stockLabel.setForeground(java.awt.Color.BLUE);
        }
        categoryLabel.setText(product.getCategory());
        idLabel.setText(String.valueOf(product.getId()));
    }

    public Product getProduct() {
        return this.product;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        wishlistButton = new javax.swing.JPanel();
        addToWishLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        deleteCheckBox = new javax.swing.JCheckBox();
        editButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(800, 150));
        setMinimumSize(new java.awt.Dimension(800, 150));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 150));

        imageLabel.setText("   image here");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageLabel.setMaximumSize(new java.awt.Dimension(128, 128));
        imageLabel.setMinimumSize(new java.awt.Dimension(128, 128));
        imageLabel.setPreferredSize(new java.awt.Dimension(128, 128));

        nameLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nameLabel.setText("name here");

        brandLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        brandLabel.setText("brand here");

        priceLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        priceLabel.setText("price here");

        stockLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        stockLabel.setText("amount in stock here");

        wishlistButton.setMaximumSize(new java.awt.Dimension(80, 80));
        wishlistButton.setMinimumSize(new java.awt.Dimension(80, 80));
        wishlistButton.setPreferredSize(new java.awt.Dimension(80, 80));
        wishlistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseExited(evt);
            }
        });

        addToWishLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wishlist.png"))); // NOI18N

        javax.swing.GroupLayout wishlistButtonLayout = new javax.swing.GroupLayout(wishlistButton);
        wishlistButton.setLayout(wishlistButtonLayout);
        wishlistButtonLayout.setHorizontalGroup(
            wishlistButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishlistButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addToWishLabel)
                .addGap(15, 15, 15))
        );
        wishlistButtonLayout.setVerticalGroup(
            wishlistButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishlistButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addToWishLabel)
                .addGap(15, 15, 15))
        );

        categoryLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoryLabel.setText("category here");

        idLabel.setText("id here");

        deleteCheckBox.setText("Mark for deletion");
        deleteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCheckBoxActionPerformed(evt);
            }
        });

        editButton.setMaximumSize(new java.awt.Dimension(80, 80));
        editButton.setMinimumSize(new java.awt.Dimension(80, 80));
        editButton.setPreferredSize(new java.awt.Dimension(80, 80));
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(50, 50));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 50));
        jLabel3.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout editButtonLayout = new javax.swing.GroupLayout(editButton);
        editButton.setLayout(editButtonLayout);
        editButtonLayout.setHorizontalGroup(
            editButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        editButtonLayout.setVerticalGroup(
            editButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editButtonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(brandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteCheckBox)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(wishlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(stockLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addComponent(categoryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(idLabel)
                .addGap(3, 3, 3))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(wishlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(categoryLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(idLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brandLabel)
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(deleteCheckBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stockLabel)))
                .addContainerGap(4, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wishlistButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseEntered
        // TODO add your handling code here:
        wishlistButton.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_wishlistButtonMouseEntered

    private void wishlistButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseExited
        // TODO add your handling code here:
        wishlistButton.setBackground(wishlistButton.getParent().getBackground());
    }//GEN-LAST:event_wishlistButtonMouseExited

    private void wishlistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseClicked
        // TODO add your handling code here:
        LoginForm.currentUser.addToWishlist(product);
    }//GEN-LAST:event_wishlistButtonMouseClicked

    private void deleteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCheckBoxActionPerformed
        // TODO add your handling code here:
        if (deleteCheckBox.isSelected()) {
            if (AdminClient.toDelete == null) {
                AdminClient.toDelete = new ArrayList<>();
            }
            AdminClient.toDelete.add(getProduct());
        } else {
            AdminClient.toDelete.remove(getProduct());
        }
    }//GEN-LAST:event_deleteCheckBoxActionPerformed

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        // TODO add your handling code here:
        editButton.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        // TODO add your handling code here:
        editButton.setBackground(editButton.getParent().getBackground());
    }//GEN-LAST:event_editButtonMouseExited

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        // TODO add your handling code here:
        new EditProductWindow(getProduct()).setVisible(true);
    }//GEN-LAST:event_editButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addToWishLabel;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JCheckBox deleteCheckBox;
    private javax.swing.JPanel editButton;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel wishlistButton;
    // End of variables declaration//GEN-END:variables
}
