/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ui;

import entities.Product;
import java.awt.Color;
import java.awt.Container;
import javax.swing.ImageIcon;

/**
 *
 * @author Stefan
 */
public class ProductWishlistPanel extends javax.swing.JPanel {

    private final Product product;
    /**
     * Creates new form ProductWishlistPanel
     * @param product
     */
    public ProductWishlistPanel(Product product) {
        initComponents();
        this.product = product;
        imageLabel.setIcon(new ImageIcon(product.getImagePath()));
        nameLabel.setText(product.getName());
        brandLabel.setText(product.getBrand());
        priceLabel.setText("$" + String.valueOf(product.getPrice()));
        stockLabel.setText("In stock: " + String.valueOf(product.getStock()));
        if (product.getStock() == 0) {
            stockLabel.setForeground(java.awt.Color.RED);
        } else {
            stockLabel.setForeground(java.awt.Color.BLUE);
        }
        categoryLabel.setText(product.getCategory());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        wishlistButton = new javax.swing.JPanel();
        addToWishLabel = new javax.swing.JLabel();
        categoryLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMaximumSize(new java.awt.Dimension(530, 150));
        setMinimumSize(new java.awt.Dimension(530, 150));
        setPreferredSize(new java.awt.Dimension(530, 150));

        imageLabel.setText("   image here");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imageLabel.setMaximumSize(new java.awt.Dimension(128, 128));
        imageLabel.setMinimumSize(new java.awt.Dimension(128, 128));
        imageLabel.setPreferredSize(new java.awt.Dimension(128, 128));

        nameLabel.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        nameLabel.setText("name here");

        brandLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        brandLabel.setText("brand here");

        priceLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        priceLabel.setText("price here");

        stockLabel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        stockLabel.setText("amount in stock here");

        wishlistButton.setMaximumSize(new java.awt.Dimension(80, 80));
        wishlistButton.setMinimumSize(new java.awt.Dimension(80, 80));
        wishlistButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                wishlistButtonMouseExited(evt);
            }
        });

        addToWishLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/wishlist.png"))); // NOI18N

        javax.swing.GroupLayout wishlistButtonLayout = new javax.swing.GroupLayout(wishlistButton);
        wishlistButton.setLayout(wishlistButtonLayout);
        wishlistButtonLayout.setHorizontalGroup(
            wishlistButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, wishlistButtonLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(addToWishLabel)
                .addGap(15, 15, 15))
        );
        wishlistButtonLayout.setVerticalGroup(
            wishlistButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(wishlistButtonLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(addToWishLabel)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        categoryLabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        categoryLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        categoryLabel.setText("category here");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(brandLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wishlistButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoryLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addGap(16, 16, 16)
                                .addComponent(brandLabel)
                                .addGap(18, 18, 18)
                                .addComponent(priceLabel))
                            .addComponent(wishlistButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stockLabel)
                            .addComponent(categoryLabel))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wishlistButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseEntered
        // TODO add your handling code here:
        wishlistButton.setBackground(new Color(204,204,255));
    }//GEN-LAST:event_wishlistButtonMouseEntered

    private void wishlistButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseExited
        // TODO add your handling code here:
        wishlistButton.setBackground(wishlistButton.getParent().getBackground());
    }//GEN-LAST:event_wishlistButtonMouseExited

    private void wishlistButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wishlistButtonMouseClicked
        // TODO add your handling code here:
        LoginForm.currentUser.removeFromWishlist(product);
        Container cont = getParent();
        cont.remove(this);
        cont.revalidate();
        cont.repaint();
    }//GEN-LAST:event_wishlistButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addToWishLabel;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JLabel categoryLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel wishlistButton;
    // End of variables declaration//GEN-END:variables
}
